server:
  port: 8010

spring:
  security:
    user:
      # user / 123
      name: user
      password: $2a$04$kqRvgmJBlWZQQ2c9NT9IH.ZhxFY07Y2xE73vmLHxBq2hNTvGvUc5m
      roles: USER

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope:
        - read
        - write
      authorized-grant-types:
        - authorization_code
        - client_credentials
        - refresh_token
        - password
      registered-redirect-uri:
        - http://localhost:8082/lsso-client/login/oauth2/code/custom
        - http://localhost:8082/lsso-client

    authorization:
      jwt:
        key-alias: mytest
        key-store: classpath:/mytest.jks
        key-store-password: mypass
      check-token-access: permitAll()

logging.level.org.springframework.security: DEBUG
