server:
  port: 8010

spring:
  security:
    user:
      # user / pass
      name: user
      password: pass
      roles: USER

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope:
        - read
        - write
      # authorized-grant-types 默认全部
      #      authorized-grant-types:
      #        - authorization_code
      #        - client_credentials
      #        - refresh_token
      #        - password
      registered-redirect-uri:
        - http://localhost:8082/lsso-client/login/oauth2/code/custom
        - http://localhost:8082/lsso-client
    authorization:
      check-token-access: permitAll()
      token-key-access: permitAll()

logging.level.org.springframework.security: DEBUG
